var consts = [
    'Demographics',
    'SSN',
    'patient',
    'identifier',
    'name',
    'given',
    'city',
    'country',
    'state',
    'line',
    'postalCode',
    'birthDate',
    'gender',
    'telecom',
    'address',
    'contact',
    'practitioner',
    'appointment',
    'encounter',
    'Identifiers',
    'diagnosis',
    'condition',
    'race',
    'deceasedBoolean',
    'communication',
    'participant',
    'location',
    'department',
    'subject',
  ];
  
  
  module.exports = consts;